name: goreleaser

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore the Certificate and Private Key
        run: |
          echo "${{ secrets.CERT_BASE64 }}" | base64 -d > /tmp/cert.pfx
        shell: bash
      - name: Install osslsigncode
        run: sudo apt-get update && sudo apt-get install -y osslsigncode
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}